name: Validate submission and create new JSON entry for it

on: 
    issues:
      types: [opened, labeled]

jobs:
    create-json:
        if: contains(github.event.issue.labels.*.name, 'submission')

        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 24
            - name: Parse issue
              id: parse
              uses: onmax/issue-form-parser@v1.6
              with:
                issue_number: ${{ github.event.issue.number }}
            - name: Show parsed data JSON
              env:
                parsed_data: ${{ steps.parse.outputs.payload }}
              run: |
                echo "$parsed_data"

