name: Validate submission and create new JSON entry for it

on: 
    issues:
      types: [opened, labeled]

jobs:
    create-json:
        if: contains(github.event.issue.labels.*.name, 'submission')

        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 24
            - name: Parse issue
              id: parse
              uses: onmax/issue-form-parser@v1.6
              with:
                issue_number: ${{ github.event.issue.number }}
            - name: Validate data and create new JSON
              env:
                parsed_data: ${{ steps.parse.outputs.payload }}
                issue_number: ${{ github.event.issue.number }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                CHROME_STATS_API_KEY: ${{ secrets.CHROME_STATS }}
              run: node src/scripts/new-JSON.mjs
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v6
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                commit-message: "create new startpage entry"
                committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
                author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
                branch: "add-startpage-${{ github.run_id }}"
                title: "New Startpage ${{github.event.issue.title}}"
                body: "Closes #${{ github.event.issue.number }}"
                add-paths: |
                  src/content/startpages/
                  public/screenshots/

